---

# Pre-checks are performed using the more powerful Python and then displayed here

- name: "Sanitize Data"
  set_fact:
    sanitized_ssl_seq: "{{ ssl_sequence | default([]) }}"

- name: "Apply All Checks"
  set_fact:
    check_results:
     - "{{ sanitized_ssl_seq | check_sequence_names_present }}"
     - "{{ sanitized_ssl_seq | check_sequence_names_uniqe }}"
     - "{{ sanitized_ssl_seq | check_sequence_signing_type }}"
     - "{{ sanitized_ssl_seq | check_sequence_signing_keys }}"
     - "{{ sanitized_ssl_seq | check_sequence_generating_keys }}"

- name: "Validate All Checks"
  debug: msg="{{ item.message }}"
  failed_when: not item.result
  when: not item.result
  with_items:
   - "{{ check_results }}"
