---

- include: "2.1-create_private_key.yml"
  when: entity.key is defined

- include: "2.2-create_certificate.yml"
  when: entity.certificate is defined

- include: "2.3-create_chain.yml"
  when: entity.chain is defined and
        entity.chain.certificates | default([]) | length > 0
