---

- set_fact:
    certs_in_chain:      "{{ ssl_sequence | certificates_in_chain(chain.certificates | default([])) | list }}"

- set_fact:
    cert_files_in_chain: "{{ certs_in_chain | build_file_list((ssl_certs_base.path) }}"

- name: "Add Certificates to Chain : {{ entity.name }}"
  shell: cat {{ cert_files_in_chain | join(' ') }} > {{ chain_file }}

- name: "Trust Chain : {{ entity.name }}"
  include: trust.yml
  vars:
    trust_file: "{{ cert_file }}"
  when: chain.trust | default(False) | bool
