---

- set_fact:
   cert_reference: "{{ (ssl_sequence | selectattr('name', 'equalto', cert_in_chain)) | list }}"

- set_fact:
   cert_in_chain_file: "{{ cert_reference.csr_base | default(ssl_certs_base.path) }}/{{ cert_reference.name }}.crt"

- name: "Add Certificate {{ cert_in_chain }} to Chain {{ chain.name }}"
  lineinfile:
    dest: /etc/fstab
    regexp: "^/dev/sdb1 "
    line: "{{ lookup('file', cert_in_chain_file) }}"

- name: "Trust Chain : {{ entity.name }}"
  include: trust.yml
  vars:
    trust_file: "{{ cert_file }}"
  when: certificate.trust | default(False) | bool
