---
# tasks file for ssl-certs

- name: "Include OS Variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
   - "vars-{{ ansible_distribution | lower }}.yml"
   - "vars-{{ ansible_os_family | lower }}.yml"
  tags: ssl-certs

- include: "1-pre_checks.yml"
  tags: ssl-certs

- name: "Install Dependencies"
  package: name="{{ item }}" state=present
  with_items:
   - "{{ ssl_packages_dependencies }}"
  tags: ssl-certs

- name: "Create Base Directory"
  file:
    path:   "{{ ssl_base.path }}"
    state:  directory
    force:  yes
    mode:   "{{ ssl_base.mode | default(omit) }}"
    owner:  "{{ ssl_base.owner | default(omit) }}"
    group:  "{{ ssl_base.group | default(omit) }}"
    seuser: "{{ ssl_base.seuser | default(omit) }}"
    serole: "{{ ssl_base.serole | default(omit) }}"
    setype: "{{ ssl_base.setype | default(omit) }}"
  tags: ssl-certs

- include: "2-manage_entity.yml"
  with_items:
   - "{{ ssl_sequence | default([]) }}"
  when: entity.enabled | default(True) | bool
  loop_control:
    loop_var: entity
  tags: ssl-certs
