---
# tasks file for ssl-certs

- name: "Include OS Variables"
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
        - "vars-{{ ansible_distribution | lower }}.yml"
        - "vars-{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags: ssl-certs

- name: "Run pre-checks"
  include_tasks: "1-pre_checks.yml"
  tags: ssl-certs

- name: "Install Dependencies"
  package:
    name: "{{ ssl_packages_dependencies }}"
    state: present
  tags: ssl-certs

- name: "Create Base Directory"
  file:
    path:   "{{ ssl_base.path }}"
    state:  directory
    force:  true
    mode:   "{{ ssl_base.mode | default(omit) }}"
    owner:  "{{ ssl_base.owner | default(omit) }}"
    group:  "{{ ssl_base.group | default(omit) }}"
    seuser: "{{ ssl_base.seuser | default(omit) }}"
    serole: "{{ ssl_base.serole | default(omit) }}"
    setype: "{{ ssl_base.setype | default(omit) }}"
  tags: ssl-certs

- name: "Manage SSL entities"
  include_tasks: "2-manage_entity.yml"
  loop: "{{ ssl_sequence | default([]) }}"
  when: entity.enabled | default(true) | bool
  loop_control:
    loop_var: entity
  tags: ssl-certs
