---

- name: "set_fact : manage_entity.yml : {{ entity.name }}"
  set_fact:
    private_key:      "{{ entity.key | default(omit) }}"
    certificate:      "{{ entity.certificate | default(omit) }}"
    chain:            "{{ entity.chain | default(omit) }}"

- name: "set_fact : manage_entity.yml : {{ entity.name }}"
  set_fact:
    key_file:         "{{ entity.key_base | default(ssl_keys_base.path) }}/{{ entity.name }}.key"
    csr_file:         "{{ entity.csr_base | default(ssl_csr_base.path) }}/{{ entity.name }}.csr"
    cert_file:        "{{ entity.crt_base | default(ssl_certs_base.path) }}/{{ entity.name }}.crt"
    chain_file:       "{{ entity.crt_base | default(ssl_certs_base.path) }}/{{ entity.name }}-chain.crt"

- name: "set_fact : manage_entity.yml : {{ entity.name }}"
  set_fact:
    local_key_file:   "{{ entity.store_key_base | default(ssl_store_keys_base) }}/{{ entity.name }}.key"
    local_cert_file:  "{{ entity.store_crt_base | default(ssl_store_certs_base) }}/{{ entity.name }}.crt"
    local_chain_file: "{{ entity.store_crt_base | default(ssl_store_certs_base) }}/{{ entity.name }}-chain.crt"

- include: "create_private_key.yml"
  when: entity.key is defined

- include: "create_certificate.yml"
  when: entity.certificate is defined

- include: "create_chain.yml"
  when: entity.chain is defined and
        entity.chain.certificates | default([]) | length > 0
